### ISSUE TITLE
[IMPORTANT] "Select Mother Tongue" list does not show on new user form

### ISSUE THREAD

**Issue by geoff-igiari** [toby-1-kenobi/sag_reporter#57]
**environment**: lcreporter-test
**priority of issue:** Should be fixed ASAP
**issue reproducible in:** all browsers

**impact of issue:**
Admins are not able to create new users (a key function of the admin role). This is because you get an error message preventing you from creating the user since mother tongue cannot be null.

![user_error](https://cloud.githubusercontent.com/assets/15933209/11385761/0108cf8c-9370-11e5-8c96-8009f795142b.png)

**Steps to reproduce**
1. Login as admin
2. Click "view all users" from home page
3. Click "Add User"
4. Hover and/or click the "Select Mother Tongue" list on the "new user" form (see below)
5. If you edit an existing user the "Select Mother Tongue" list actually shows a list upon click

![new_user_form](https://cloud.githubusercontent.com/assets/15933209/11385786/486f8122-9370-11e5-882f-2a2803bde0e1.png)

**Comment by toby-1-kenobi** [comment]
The reason is that there are no options under that control, because the options are filtered according to what state(s) you have selected (there's too many languages in the system to show them all here at once - that's why the filtering is necessary) when you create a new user there are no states selected to begin with and so no languages show in the dropdown.

The state selection is hidden in this screenshot because it is also filtered according to zone, and when it is empty it hides. I think probably the language dropdowns should hide too when they are empty to be consistent.

**Comment by geoff-igiari** [comment]
Okay - thanks for the info. 

I agree that the language dropdown should behave like the other dropdowns for consistency.

**Comment by toby-1-kenobi** [comment]
OK, now all empty dropdowns on this page get hidden
